version: '3.8'

services:
  # Слой базы данных PostgreSQL
  postgres_db:
    image: postgres:15-alpine
    container_name: tg_bot_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: tgbot_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  tg_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_telegram_bot
    restart: always
    depends_on:
      - postgres_db
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: tgbot_db
    network_mode: "host" 

volumes:
  pgdata:
